// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehjkykckzkowalyhuorc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoamt5a2Nremtvd2FseWh1b3JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MzU1NjEsImV4cCI6MjA2NDAxMTU2MX0.iVstOlODBchRE3FzzBIi7vzUVWH4zQimh-Adg4jIU3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);